# Week 1 - Introduction

### Excercise - 1

In [5]:
print("Hello World")
print("what's your name ?")
name = input()
print("It's goog to meet you, " + name)
print("Your name is of length " + str(len(name)))
print("whats's your age ? ")
age = input()
print("You will be "+str(int(age)+1)+" years old in a year")

Hello World
what's your name ?


 Ajul


It's goog to meet you, Ajul
Your name is of length 4
whats's your age ? 


 27


You will be 28 years old in a year


### Excercise - 2 

In [11]:
import numpy as np

print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

In [19]:
a = np.arange(10)
# a.ndim
# a.shape
# a.size

1

In [21]:
z = np.zeros(10)
z.shape

(10,)

In [27]:
ar = np.arange(10, 51)

In [28]:
np.flip(ar)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

In [30]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
values = [1,2,0,0,4,0]

In [33]:
np.nonzero(values)

(array([0, 1, 4], dtype=int64),)

In [34]:
np.random.rand(3,3,3)

array([[[0.64972488, 0.43043214, 0.45908175],
        [0.05840861, 0.5443019 , 0.76959131],
        [0.88336894, 0.86287448, 0.42781325]],

       [[0.56462561, 0.09283394, 0.60955775],
        [0.80514002, 0.91165503, 0.14244558],
        [0.82510831, 0.65159305, 0.08066789]],

       [[0.45425043, 0.50170915, 0.25424418],
        [0.16795641, 0.83837875, 0.44821482],
        [0.68578824, 0.93713901, 0.57160288]]])

In [37]:
rand_ten = np.random.rand(10,10)
rand_ten

array([[0.20797275, 0.44605202, 0.43599087, 0.56652224, 0.28115736,
        0.12861844, 0.56546567, 0.50570238, 0.66598202, 0.11822404],
       [0.86979662, 0.97238444, 0.77872923, 0.08789247, 0.88973752,
        0.60797359, 0.37591358, 0.65368214, 0.71105891, 0.25480456],
       [0.69698265, 0.17722766, 0.91861112, 0.58240374, 0.24924861,
        0.81196381, 0.57494417, 0.52503769, 0.16364461, 0.20483898],
       [0.56510808, 0.81667289, 0.54536761, 0.58332637, 0.08144292,
        0.79487846, 0.77256533, 0.67621115, 0.23618858, 0.7582236 ],
       [0.92907131, 0.2141553 , 0.07390286, 0.77282632, 0.40310976,
        0.73812428, 0.89582205, 0.96502741, 0.26043261, 0.8714708 ],
       [0.50215582, 0.73242148, 0.98384677, 0.6385729 , 0.6259941 ,
        0.08383909, 0.97888412, 0.1693354 , 0.93309054, 0.8240597 ],
       [0.94149541, 0.01031847, 0.39620786, 0.81325628, 0.12713286,
        0.04457063, 0.24866572, 0.59584918, 0.68591249, 0.00790757],
       [0.91995485, 0.87547338, 0.1938137

In [38]:
np.max(rand_ten)

0.9838467707479538

In [39]:
np.min(rand_ten)

0.007907566972787161

In [40]:
rand_thirty = np.random.rand(30)
rand_thirty

array([0.49036283, 0.27861382, 0.04201078, 0.760032  , 0.43344494,
       0.64390202, 0.72520606, 0.30823849, 0.45098877, 0.44851524,
       0.89128057, 0.48865447, 0.31490029, 0.71573991, 0.26667093,
       0.59352392, 0.03864086, 0.90176468, 0.61058687, 0.12354383,
       0.07800835, 0.94384703, 0.30456936, 0.82829148, 0.94926836,
       0.5726025 , 0.96854156, 0.76789945, 0.81755515, 0.90603306])

In [41]:
np.mean(rand_thirty)

0.5554412532810231

In [43]:
x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
m1 = np.random.rand(5,3)
m1

array([[0.28124672, 0.96370479, 0.03950715],
       [0.90777592, 0.16209906, 0.10929917],
       [0.79196289, 0.53251179, 0.3572762 ],
       [0.67171759, 0.50353685, 0.6257316 ],
       [0.48879334, 0.38292625, 0.02945543]])

In [47]:
m2 = np.random.rand(3,2)
m2

array([[0.61151285, 0.49794271],
       [0.20772095, 0.68653698],
       [0.58151661, 0.10551395]])

In [48]:
np.dot(m1,m2)

array([[0.39514173, 0.80583228],
       [0.6523473 , 0.57483999],
       [0.80267138, 0.7976388 ],
       [0.87923241, 0.74619696],
       [0.39557404, 0.50939207]])

In [49]:
np.matmul(m1,m2)

array([[0.39514173, 0.80583228],
       [0.6523473 , 0.57483999],
       [0.80267138, 0.7976388 ],
       [0.87923241, 0.74619696],
       [0.39557404, 0.50939207]])

In [53]:
a1 = np.arange(1,5)
a2 = np.arange(2,6)

In [54]:
a1

array([1, 2, 3, 4])

In [55]:
a2

array([2, 3, 4, 5])

In [56]:
a1*a2

array([ 2,  6, 12, 20])